Include page object utility in nimble-components build output (#2290)
# Pull Request

## 🤨 Rationale

We added the combobox page object in #2255 and #2286. When I tried to
use it in SLE I got a build error saying "Error: Module not found:
Error: Can't resolve '../../utilities/tests/component' in
'..../SystemLinkShared/node_modules/@ni/nimble-components/dist/esm/combobox/testing'"

That import is a dependency of the page object but because it lives in a
folder called "tests", [the .npmignore
file](https://github.com/ni/nimble/blob/main/packages/nimble-components/.npmignore)
doesn't include it in the built package contents.

This also impacts the menu button page object.

## 👩‍💻 Implementation

1. Move `src/utilities/tests/component.ts` to
`src/utilities/testing/component.ts` and update callers.
2. Add README.md to several utilities directories explaining their
purpose. The general rule is that all of it should be considered
internal. Some of it is used externally but that's tracked by tech debt
like #2107.

Longer term we could probably catch issues like this earlier by
explicitly exporting certain paths from the nimble-components
package.json, which would mean that nimble-angular's build would have
failed. This is tracked by #172.

## 🧪 Testing

Verified that the output of `npm run pack -w @ni/nimble-components` now
includes the `testing/components` dependency. I will test this in SLE
post-release and address any remaining issues in a follow-up.

## ✅ Checklist

<!--- Review the list and put an x in the boxes that apply or ~~strike
through~~ around items that don't (along with an explanation). -->

- [x] I have updated the project documentation to reflect my changes or
determined no changes are needed.

---------

Co-authored-by: Milan Raj <rajsite@users.noreply.github.com>