NPM Dependency Updates January 2025 (#2504)
# Pull Request

## 🤨 Rationale

Follow-up from https://github.com/ni/nimble/pull/2501 and
https://github.com/ni/nimble/pull/2499

## 👩‍💻 Implementation

- Updated the major dependencies covered in the above mentioned PR
- Did not pull-in React 19 updates yet, seems supported in storybook,
will give it a try in a follow-on PR or create a tech debt:
https://github.com/storybookjs/storybook/issues/29805
- Rebuilt the lock file to pull in latest versions in semver range
- Had to make peerDependencies on React 18 types as the v19 types got
pulled in on rebuild of lock file and caused issues in mdx typing (the
JSX namespace was deprecated in React 18 and removed in React 19):
     ```
Error: ../../node_modules/@types/mdx/types.d.ts(23,38): error TS2503:
Cannot find namespace 'JSX'.
Error:
../../node_modules/@types/mdx/types.d.ts([28](https://github.com/ni/nimble/actions/runs/12565897794/job/35030682905#step:12:29),23):
error TS2503: Cannot find namespace 'JSX'.
Error: ../../node_modules/@types/mdx/types.d.ts(47,28): error TS2503:
Cannot find namespace 'JSX'.
Error: ../../node_modules/@types/mdx/types.d.ts(73,46): error TS2503:
Cannot find namespace 'JSX'.
     ```
- Removed the webpack-cli dep which seems unused (we don't see to use
the command in any scripts)

## 🧪 Testing

Rely on CI

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or
determined no changes are needed.