Turn on stricter type checking for nimble-components (#243)
## 🤨 Rationale

Resolves #222 

## 👩‍💻 Implementation

I set `"strict": true` and fixed as many violations as I could. Most of these were simple, like adding an initializer, adding parameter names to arrow function types, or using `!` to mark variables as exempt from initialization checking.

The only strict option I had to disable was `strictFunctionTypes`, because there are violations at every `compose` call where we pass in the FAST template:

```
src/checkbox/index.ts:15:5 - error TS2322: Type '(context: ElementDefinitionContext, definition: CheckboxOptions) => ViewTemplate<Checkbox, any>' is not assignable to type 'EagerOrLazyFoundationOption<ElementViewTemplate, CheckboxOptions> | undefined'.
  Type '(context: ElementDefinitionContext, definition: CheckboxOptions) => ViewTemplate<Checkbox, any>' is not assignable to type 'LazyFoundationOption<ElementViewTemplate, CheckboxOptions>'.
    Types of parameters 'definition' and 'definition' are incompatible.
      Type 'OverrideFoundationElementDefinition<CheckboxOptions>' is not assignable to type 'CheckboxOptions'.
        Type 'OverrideFoundationElementDefinition<CheckboxOptions>' is not assignable to type 'FoundationElementDefinition'.
          Types of property 'baseName' are incompatible.
            Type 'string | undefined' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.

15     template,
       ~~~~~~~~

  ../../node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:4030:14
    4030     readonly template?: EagerOrLazyFoundationOption<ElementViewTemplate, this>;
                      ~~~~~~~~
    The expected type comes from property 'template' which is declared here on type 'CheckboxOptions'
```

## 🧪 Testing

Built without violations, and tests passed.

## ✅ Checklist

- [X] I have updated the project documentation to reflect my changes or determined no changes are needed.