Fix broken import of non-exported file (#2526)
# Pull Request

## 🤨 Rationale

When trying to use `RichTextEditorPageObject` from a client, I ran into
a missing import build failure:

```
Error: node_modules/@ni/nimble-components/dist/esm/rich-text/editor/testing/types.d.ts:2:42 - error TS2307: Cannot find module '../../../rich-text-mention/base/tests/rich-text-mention.fixtures' or its corresponding type declarations.

2 import type { RichTextMentionTest } from '../../../rich-text-mention/base/tests/rich-text-mention.fixtures';
```

## 👩‍💻 Implementation

The problem is that `rich-text-editor.pageobject.ts` imports from its
sibling `types.ts` file, which in turn was importing from
`rich-text-mention.fixtures.ts` (in the `rich-text-mention/base/tests`
directory). That file is test-only and not included in
`nimble-components`, so `rich-text/editor/testing/types.ts` (which _is_
part of `nimble-components`) should never have been importing from it.

I moved a couple types (`UserMentionElements` and `TestMentionElements`)
out of `types.ts` and into `rich-text-editor-utils.ts` to avoid the
issue.

## 🧪 Testing

Built and zipped my updated version of `nimble-components` and was able
to successfully use `RichTextEditorPageObject` from some SLE tests.

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or
determined no changes are needed.

---------

Co-authored-by: Milan Raj <rajsite@users.noreply.github.com>