Dependency Update October 2025 (#2710)
Performs the following changes:
- Updates npm dependencies, except:
- Known don't upgrades: angular v20 (and ng-packagr and zone.js), ni
eslint v9 packages, tiptap v3, react v19, typescript >v5.4.5
- `@vitejs/plugin-react-swc` upgrading caused type and build errors I
did not investigate
  - yargs major update requires source changes, didn't look into it
- newly pinned peer `flatbuffers`. [TypeScript 5.7 changed the
definitions of Int32Array to include a
generic](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-7.html#support-for---target-es2024-and---lib-es2024).
The flatbuffers library used by apache-arrow [updated to a newer version
of typescript](https://github.com/google/flatbuffers/pull/8620) and now
emits types that rely on Int32 being generic. Because we do full type
lib checks this causes an issue and TypeScript fails with `Error TS2315:
Type 'Int32Array' is not generic.` messages. Added a peer dep on the
older `flatbuffers` version to avoid the issue. When the Angular upgrade
is done and corresponding TypeScript update we can remove that pinned
per `flatbuffers` dep.
- Updates nuget deps, except:
  - Known don't upgrades: dotnet v9
- Following the [Manual Recurring update task on
playwright](https://github.com/ni/nimble/issues/1747) I tried to find
the latest playwright version is 1.55.0 which has a [DriverVersion /
node dependency version on
`playwright@1.55.0-beta-1756314050000`](https://github.com/microsoft/playwright-dotnet/blob/v1.55.0/src/Common/Version.props#L5).
This [seems
intentional](https://github.com/microsoft/playwright-dotnet/pull/3234#discussion_r2402444164)
right now so I instead went with the [last
release](https://github.com/microsoft/playwright-dotnet/blob/v1.54.0/src/Common/Version.props#L5)
of `playwright-dotnet@1.54.0` and `playwright@1.54.1`
- This update ends up pulling in the stylistic update in the ni eslint
packages and applies formatting changes for it.
- Updates `template.ts` files to opt-out of prettier linting altogether
(33 of 62 files already manually were) and the `@stylistic/indent`
eslint rule.
- Known workflow issues: With the latest Visual Studio installed and
with the dotnet-sdk v8 version we specify in the globals.json file it is
not possible to run `npm run -w packages\blazor-workspace
update-lock-files` reliably. It will lock to assembly versions that are
not part of the sdk installation, see [dotnet
issue](https://github.com/dotnet/sdk/issues/38200). The best workaround
I have so far is to sync the changes in WSL, [nuke any existing dotnet
installs in
WSL](https://github.com/dotnet/sdk/issues/39635#issuecomment-3075858666),
download the x64 sdk, [manually install
it](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#example),
and then update lock files to push to the branch.
- Updates renovate.json to opt-out of package-lock.json updates and npm
`@ni` package updates as separate workflows. Getting the notification
for general package.json updates periodically is good enough as updates
are a very manual process right now.

<details>
<summary>Renovate Blazor Update Details</summary>
> [!NOTE]
> Mend has cancelled [the proposed
renaming](https://redirect.github.com/renovatebot/renovate/discussions/37842)
of the Renovate GitHub app being renamed to `mend[bot]`.
> 
> This notice will be removed on 2025-10-07.

<hr>

This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [Microsoft.AspNetCore.Components.Web](https://asp.net/)
([source](https://redirect.github.com/dotnet/aspnetcore)) | `8.0.19` ->
`8.0.20` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/Microsoft.AspNetCore.Components.Web/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/Microsoft.AspNetCore.Components.Web/8.0.19/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[Microsoft.AspNetCore.Components.WebAssembly.DevServer](https://asp.net/)
([source](https://redirect.github.com/dotnet/aspnetcore)) | `8.0.19` ->
`8.0.20` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/Microsoft.AspNetCore.Components.WebAssembly.DevServer/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/Microsoft.AspNetCore.Components.WebAssembly.DevServer/8.0.19/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [Microsoft.AspNetCore.Components.WebAssembly.Server](https://asp.net/)
([source](https://redirect.github.com/dotnet/aspnetcore)) | `8.0.19` ->
`8.0.20` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/Microsoft.AspNetCore.Components.WebAssembly.Server/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/Microsoft.AspNetCore.Components.WebAssembly.Server/8.0.19/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [Microsoft.AspNetCore.Components.WebView](https://asp.net/)
([source](https://redirect.github.com/dotnet/aspnetcore)) | `8.0.19` ->
`8.0.20` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/Microsoft.AspNetCore.Components.WebView/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/Microsoft.AspNetCore.Components.WebView/8.0.19/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [Microsoft.AspNetCore.Mvc.Testing](https://asp.net/)
([source](https://redirect.github.com/dotnet/aspnetcore)) | `8.0.19` ->
`8.0.20` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/Microsoft.AspNetCore.Mvc.Testing/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/Microsoft.AspNetCore.Mvc.Testing/8.0.19/8.0.20?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[xunit.runner.visualstudio](https://redirect.github.com/xunit/visualstudio.xunit)
| `3.1.3` -> `3.1.5` |
[![age](https://developer.mend.io/api/mc/badges/age/nuget/xunit.runner.visualstudio/3.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/nuget/xunit.runner.visualstudio/3.1.3/3.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>dotnet/aspnetcore
(Microsoft.AspNetCore.Components.Web)</summary>

###
[`v8.0.20`](https://redirect.github.com/dotnet/aspnetcore/releases/tag/v8.0.20):
.NET 8.0.20

[Release](https://redirect.github.com/dotnet/core/releases/tag/v8.0.20)

##### What's Changed

- Update branding to 8.0.20 by
[@&#8203;vseanreesermsft](https://redirect.github.com/vseanreesermsft)
in
[#&#8203;63106](https://redirect.github.com/dotnet/aspnetcore/pull/63106)
- \[release/8.0] (deps): Bump src/submodules/googletest from `c67de11`
to `373af2e` by
[@&#8203;dependabot](https://redirect.github.com/dependabot)\[bot] in
[#&#8203;63038](https://redirect.github.com/dotnet/aspnetcore/pull/63038)
- \[release/8.0] Dispose the certificate chain elements with the chain
by [@&#8203;MackinnonBuck](https://redirect.github.com/MackinnonBuck) in
[#&#8203;62994](https://redirect.github.com/dotnet/aspnetcore/pull/62994)
- \[release/8.0] Update SignalR Redis tests to use internal Docker Hub
mirror by
[@&#8203;github-actions](https://redirect.github.com/github-actions)\[bot]
in
[#&#8203;63117](https://redirect.github.com/dotnet/aspnetcore/pull/63117)
- \[release/8.0] \[SignalR] Don't throw for message headers in Java
client by
[@&#8203;github-actions](https://redirect.github.com/github-actions)\[bot]
in
[#&#8203;62784](https://redirect.github.com/dotnet/aspnetcore/pull/62784)
- Merging internal commits for release/8.0 by
[@&#8203;vseanreesermsft](https://redirect.github.com/vseanreesermsft)
in
[#&#8203;63152](https://redirect.github.com/dotnet/aspnetcore/pull/63152)
- \[release/8.0] Update dependencies from dotnet/extensions by
[@&#8203;dotnet-maestro](https://redirect.github.com/dotnet-maestro)\[bot]
in
[#&#8203;63188](https://redirect.github.com/dotnet/aspnetcore/pull/63188)
- \[release/8.0] Update dependencies from dotnet/arcade by
[@&#8203;dotnet-maestro](https://redirect.github.com/dotnet-maestro)\[bot]
in
[#&#8203;63189](https://redirect.github.com/dotnet/aspnetcore/pull/63189)

**Full Changelog**:
<https://github.com/dotnet/aspnetcore/compare/v8.0.19...v8.0.20>

</details>

<details>
<summary>xunit/visualstudio.xunit (xunit.runner.visualstudio)</summary>

###
[`v3.1.5`](https://redirect.github.com/xunit/visualstudio.xunit/compare/3.1.4...3.1.5)

[Compare
Source](https://redirect.github.com/xunit/visualstudio.xunit/compare/3.1.4...3.1.5)

###
[`v3.1.4`](https://redirect.github.com/xunit/visualstudio.xunit/compare/3.1.3...3.1.4)

[Compare
Source](https://redirect.github.com/xunit/visualstudio.xunit/compare/3.1.3...3.1.4)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "monthly" (UTC), Automerge - At any
time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ni/nimble).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xMzEuOSIsInVwZGF0ZWRJblZlciI6IjQxLjEzMS45IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->
</details>

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: rajsite <rajsite@users.noreply.github.com>
Co-authored-by: rajsite <1588923+rajsite@users.noreply.github.com>