Avoid duplicate imports in storybook for spright components (#2567)
# Pull Request

## 🤨 Rationale

Fixes https://github.com/ni/nimble/issues/2528

- Last year when introducing the spright package in the monorepo,
storybook was split out into a separate package.
- Placing storybook in a separate package [broke
turbosnap](https://github.com/ni/nimble/issues/2118) as import paths
referenced package identifiers and not paths to files in git (build
output in dist vs checked in src)
- A [workaround](https://github.com/ni/nimble/pull/2131) was introduced
to reference source paths across package boundaries directly 🤒.
- The workaround [breaks if a spright component depends on a nimble
component](https://github.com/ni/nimble/issues/2528) because storybook
will have an absolute reference, i.e. text field story
`../../../../nimble-components/src/text-field` and in the spright
component `@ni/nimble-components/dist/esm/text-field`

## 👩‍💻 Implementation

- Found a [storybook
issue](https://github.com/storybookjs/storybook/issues/14087#issuecomment-1339108022)
that described the package
[`tsconfig-paths-webpack-plugin`](https://github.com/dividab/tsconfig-paths-webpack-plugin)
where we can define a tsconfig path that gets types to resolve correctly
and the same paths are picked up by webpack so the resulting build also
uses the same source path.
- Added tsconfig paths that redirect `@ni/nimble-components/dist/esm/`
imports to `@ni/nimble-components/src`
- Added tsconfig paths that redirect `@ni/spright-components/dist/esm/`
imports to `@ni/spright-components/src`

Alternatives / potential future work:
- We might be able to switch back to normal imports in storybook across
all files and rely more heavily on the plugin to redirect `dist/esm`
imports to `src`. I did not attempt this or validate that turbosnap
would still function with that change.
- There is a corresponding chromatic issue where others have ran into
problems with similar monorepo setups. Once resolved hopefully we can
remove all the workarounds. See
https://github.com/chromaui/chromatic-cli/issues/1149

## 🧪 Testing

- Created a [test
commit](https://github.com/ni/nimble/pull/2567/commits/0eb68e5c161318f9e0bd8249b14c01239c1c91b9)
where the [build
failed](https://github.com/ni/nimble/actions/runs/14073130172/job/39411209846#step:12:221):
   ```
Error: ../nimble-components/dist/esm/text-field/index.d.ts(5,9): error
TS2717: Subsequent property declarations must have the same type.
Property ''nimble-text-field'' must be of type 'TextField', but here has
type 'TextField'.
   ```
- [Applied the
webpack](https://github.com/ni/nimble/pull/2567/commits/b8bc960d94237bd7911dc302dbe48b2172a0b086)
and tsconfig path changes and the build passed

## ✅ Checklist

- [x] I have updated the project documentation to reflect my changes or
determined no changes are needed.